### ISSUE TITLE
Is This A Dupe?

### ISSUE THREAD

**Issue by sherl0cks** [radanalyticsio/jupyter-notebook#1]
https://github.com/radanalyticsio/base-notebook appears to provide the same functionality (Jupyter with python 2.7 and spark). Is there a reason for this? https://github.com/radanalyticsio/base-notebook is currently linked from https://radanalytics.io/tutorials

**Comment by sherl0cks** [comment]
closed via https://github.com/radanalyticsio/base-notebook/issues/12#issuecomment-352106722

**Comment by sub-mod** [comment]
We have TODO activity to replace base-notebook with jupyter-notebook-py3.5 OR jupyter-notebook-py2.7 in https://radanalytics.io/tutorials.
For all new work kindly use jupyter-notebook-py3.5 (for jupyterlab) or jupyter-notebook-py2.7
